site_name: TMD - TrueMap Data Library
site_description: A Python library for processing and analyzing TrueMap Data files
site_author: Antoine

repo_url: https://github.com/ETSTribology/TrueMapData
edit_uri: ""

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide:
    - Getting Started: user-guide/getting-started.md
    - File Formats: user-guide/file-formats.md
    - Basic Usage: user-guide/basic-usage.md
    - Exporting Data: user-guide/exporting.md
  - Architecture:
    - Overview: architecture/overview.md
    - Data Flow: architecture/data-flow.md
    - Component Diagram: architecture/component-diagram.md
