site_name: TMD Library
site_url: https://github.com/ETSTribology/TrueMapData
site_description: TrueMap Data (TMD) file processing library
site_author: Antoine Gagnon
repo_url: https://github.com/ETSTribology/TrueMapData
repo_name: ETSTribology/TrueMapData

nav:
  - Home: index.md
  - User Guide:
    - Installation: user-guide/installation.md
    - Getting Started: user-guide/getting-started.md
    - Working with TMD Files: user-guide/working-with-tmd-files.md
    - Visualization: user-guide/visualization.md
    - Exporting Data: user-guide/exporting-data.md
  - Architecture:
    - Overview: architecture/overview.md
    - Component Diagram: architecture/component-diagram.md
    - Data Flow: architecture/data-flow.md
  - API Reference:
    - Processor: api/processor.md
    - Filter Module: api/filter.md
    - Processing Module: api/processing.md
    - Exporters:
      - Image Exporter: api/exporters/image.md
      - 3D Model Exporter: api/model.md
      - Compression: api/compression.md
    - Visualization: api/visualization.md
  - License: https://github.com/ETSTribology/TrueMapData/blob/main/LICENSE

theme:
  name: material
  palette:
    primary: blue
    accent: teal
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ETSTribology
      name: ETSTribology on GitHub

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [tmd]
          options:
            show_source: true
            show_if_no_docstring: false
            heading_level: 3
            members_order: source
            docstring_style: google
            docstring_section_style: table
            filters: ["!^_"]
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
            separate_signature: true
