name: Documentation

on:
  push:
    branches: [ main, master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for git-revision-date-localized plugin
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs==1.5.3 mkdocs-material==9.4.14
        pip install mkdocstrings mkdocstrings-python
        pip install pymdown-extensions
        pip install mkdocs-git-revision-date-localized-plugin
        pip install -e .
    
    - name: Build documentation
      run: |
        mkdocs build
    
    - name: Deploy to GitHub Pages
      if: success() && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        publish_branch: docs  # Specify the branch to which the documentation should be published
